package com.trycatch;

public class Main {
	/*void foo() throws NullPointerException{
	try{
		String s = "Str";
		System.out.println(s);
	
	try{
		System.out.println(s.length());
	//	System.out.println(s.substring(3,4));
	} catch(NullPointerException e){
		System.out.println("inner");
		//throw new NullPointerException();
	}
	System.out.println("2");
	}
	catch(NullPointerException e){
		System.out.println("outer");
	}
	
	}*/
	/*private int i; 
	public static void someMethod(){
		System.out.println(i);       //i is private so we canot access
	}*/
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int i = 2;
		Main m = new Main();
		//m.foo();
		//m.someMethod();

	}

}
